name: 'Commit Bitmap'
description: 'Commit the bitmap file after tag and export'
branding: 
  icon: 'git-commit'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
  skip-push:
    description: "Skip commit push (for testing)"
    required: false
  skip-ci:
    description: "Remove adding [skip-ci] to the .bitmap file commit message"
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
